(() => {
  const STORAGE_KEY = 'inkyFoxBrief:v4';
  const SCRIPT_URL = 'https://script.google.com/macros/s/AKfycbz06rYAjbywJ6CS5yUHYVgi7-O6FDV-xbsHAh7UBQLbdGwlgXbL0DFuPDCfsfxPjYKw/exec';
  const assets = {
    laptop: 'assets/fox-laptop.webp',
    idea: 'assets/fox-idea.webp',
    sleep: 'assets/fox-sleep.webp',
    paw: 'assets/paw-pink-big.png',
    trail: 'assets/trail-mixed.png',
    tail: 'assets/tail.png',
    splashPink: 'assets/splash-pink.png',
    splashBlue: 'assets/splash-blue.png',
    splashMint: 'assets/splash-mint.png',
    sparkPink: 'assets/spark-pink.png',
    sparkBlue: 'assets/spark-blue.png'
  };
  const initialData = {name:'',telegram:'',projectName:'',projectTypes:[],projectTypeOther:'',projectDescription:'',userGoal:'',audience:'',trafficSources:[],trafficOther:'',afterPage:'',funnel:'',hasScenarios:'',scenarios:'',mustHave:'',textStatus:'',textOwner:'',designStatus:'',designRefs:'',integrations:[],integrationOther:'',launchDate:'',readyDate:'',importantDates:'',projectLifetime:'',futureUpdates:'',important:'',avoid:'',extra:''};
  const steps = [
    {id:'contact', kicker:'Знакомство', title:'Для начала — как к вам обращаться?', description:'Оставьте имя и Telegram, чтобы бриф не потерялся среди проектов.'},
    {id:'project', kicker:'01 · О проекте', title:'Что нужно собрать?', description:'Можно выбрать несколько вариантов. Архитектуру и блоки я продумываю сама — здесь важен общий формат.'},
    {id:'projectDescription', kicker:'01 · О проекте', title:'Коротко опишите задачу своими словами', description:'Что должно получиться в результате? Расскажите простыми словами, без технических терминов.'},
    {id:'goal', kicker:'02 · Цель', title:'Что должен сделать пользователь?', description:'Какое действие будет главным и для кого создаётся проект.'},
    {id:'funnelA', kicker:'03 · Воронка', title:'Откуда человек приходит и куда идёт дальше?', description:'Так станет понятен контекст страницы / MiniApp и её место в воронке.'},
    {id:'funnelB', kicker:'03 · Воронка', title:'Есть ли уже понимание сценария целиком?', description:'Можно описать цепочку в одну строку. Если есть разные ветки — тоже отметьте.'},
    {id:'inside', kicker:'04 · Что должно быть внутри', title:'Что обязательно должно быть реализовано?', description:'Только то, без чего проект точно не состоится. Если жёстких требований нет — структуру и механику предложу сама.'},
    {id:'texts', kicker:'05 · Тексты', title:'Что сейчас с текстами?', description:'Нужно понять исходную точку и нужна ли помощь с упаковкой.'},
    {id:'design', kicker:'06 · Дизайн', title:'Как будем работать с визуалом?', description:'Если есть фирменный стиль, брендбук или референсы — добавьте ссылки или краткое описание.'},
    {id:'integrations', kicker:'07 · Интеграции', title:'С чем нужно связать проект?', description:'Можно выбрать несколько вариантов. Доступы и технические нюансы на этом этапе не нужны.'},
    {id:'dates', kicker:'08 · Сроки', title:'Когда проект должен выйти?', description:'Если даты ещё плавают — заполняйте только то, что уже известно.'},
    {id:'after', kicker:'09 · После запуска', title:'Это разовый запуск или проект надолго?', description:'Так я заложу подходящую архитектуру и пойму, нужно ли предусматривать обновления.'},
    {id:'extra', kicker:'10 · Дополнительно', title:'Что ещё важно знать до начала работы?', description:'Последний блок — здесь можно зафиксировать пожелания, ограничения и нюансы.'},
    {id:'review', kicker:'Финал', title:'Проверьте бриф перед отправкой', description:'Если всё ок, нажмите «Отправить бриф». Ответы уйдут в таблицу автоматически.'}
  ];
  const screenEl = document.getElementById('screen'); const progressShell = document.getElementById('progressShell'); const progressLabel = document.getElementById('progressLabel'); const progressPercent = document.getElementById('progressPercent'); const progressFill = document.getElementById('progressFill'); const navRow = document.getElementById('navRow'); const backBtn = document.getElementById('backBtn'); const nextBtn = document.getElementById('nextBtn'); const saveStatus = document.getElementById('saveStatus'); const deviceNote = document.getElementById('deviceNote');
  document.getElementById('brandLink').addEventListener('click', e => { e.preventDefault(); renderIntro(); });
  let data = loadData(); let current = -1; let isSubmitting = false;
  function loadData(){ try { return { ...initialData, ...(JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null') || {}) }; } catch { return { ...initialData }; } }
  function saveData(){ localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); saveStatus.textContent = 'Сохранено'; clearTimeout(saveData._t); saveData._t = setTimeout(() => saveStatus.textContent = '', 1200); }
  const esc = (s='') => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'", '&#039;');
  const inputField=(name,label,value,opts={})=>`<div class="field"><label class="${opts.required?'required':''}" for="${name}">${esc(label)}</label>${opts.hint?`<div class="field-hint">${esc(opts.hint)}</div>`:''}<input class="${opts.type==='date'?'date-input':'text-input'}" id="${name}" name="${name}" type="${opts.type||'text'}" value="${esc(value)}" placeholder="${esc(opts.placeholder||'')}" autocomplete="off"></div>`;
  const areaField=(name,label,value,opts={})=>`<div class="field"><label class="${opts.required?'required':''}" for="${name}">${esc(label)}</label>${opts.hint?`<div class="field-hint">${esc(opts.hint)}</div>`:''}<textarea class="text-area" id="${name}" name="${name}" placeholder="${esc(opts.placeholder||'')}">${esc(value)}</textarea></div>`;
  function choices(name, items, selected, options={}){ const multi=!!options.multi; const values=multi?(Array.isArray(selected)?selected:[]):[selected]; return `<div class="choice-grid ${options.cols===3?'cols-3':''}">${items.map(item=>`<label class="choice-card"><input type="${multi?'checkbox':'radio'}" name="${name}" value="${esc(item.value)}" ${values.includes(item.value)?'checked':''}><span class="choice-body"><span class="choice-dot"></span><span class="choice-text">${esc(item.label)}</span></span></label>`).join('')}</div>`; }
  function stepShell(inner){ const s=steps[current]; return `<div class="step-screen"><img class="step-decor step-spark" src="${assets.sparkPink}" alt=""><img class="step-decor step-splash1" src="${assets.splashPink}" alt=""><img class="step-decor step-splash2" src="${assets.splashBlue}" alt=""><img class="step-decor step-trail" src="${assets.trail}" alt=""><img class="step-decor step-paw" src="${assets.paw}" alt=""><div class="step-kicker">${esc(s.kicker)}</div><h2 class="step-title">${esc(s.title)}</h2><p class="step-description">${esc(s.description)}</p>${inner}<div class="validation-message" id="validationMessage"></div></div>`; }
  function renderIntro(){ current=-1; progressShell.classList.add('is-hidden'); navRow.classList.add('is-hidden'); deviceNote.classList.add('is-hidden'); screenEl.innerHTML=`<div class="intro-grid"><div class="intro-copy"><div class="eyebrow">БРИФ · MINIAPP / WEB</div><h1>Расскажите о проекте — я соберу из этого понятную задачу на разработку</h1><p class="lead">Не нужно готовить техническое задание. Ответьте на вопросы так, как понимаете сейчас. Если чего-то ещё нет — это нормально.</p><div class="intro-points"><span>≈ 7–10 минут</span><span>можно вернуться назад</span><span>ответы не потеряются</span></div><button class="btn btn-primary btn-large" id="startBtn">Начать бриф</button></div><div class="intro-art"><div class="hero-wrap"><img class="asset splash splash-a" src="${assets.splashPink}" alt=""><img class="asset splash splash-b" src="${assets.splashBlue}" alt=""><img class="asset splash splash-c" src="${assets.splashMint}" alt=""><img class="asset tail" src="${assets.tail}" alt=""><img class="asset trail" src="${assets.trail}" alt=""><img class="asset spark-a" src="${assets.sparkPink}" alt=""><img class="asset spark-b" src="${assets.sparkBlue}" alt=""><img class="hero-fox" src="${assets.laptop}" alt="Лисёнок Inky Fox"></div></div></div>`; document.getElementById('startBtn').addEventListener('click', ()=>goTo(0)); }
  function goTo(index){ current=Math.max(0, Math.min(index, steps.length-1)); render(); window.scrollTo({top:0,behavior:'smooth'}); }
  function updateProgress(){ const pct=Math.round(((current+1)/steps.length)*100); progressLabel.textContent=`Шаг ${current+1} из ${steps.length}`; progressPercent.textContent=`${pct}%`; progressFill.style.width=`${pct}%`; }
  function render(){ progressShell.classList.remove('is-hidden'); navRow.classList.remove('is-hidden'); deviceNote.classList.remove('is-hidden'); updateProgress(); const id=steps[current].id; const map={contact:renderContact,project:renderProject,projectDescription:renderProjectDescription,goal:renderGoal,funnelA:renderFunnelA,funnelB:renderFunnelB,inside:renderInside,texts:renderTexts,design:renderDesign,integrations:renderIntegrations,dates:renderDates,after:renderAfter,extra:renderExtra,review:renderReview}; screenEl.innerHTML=stepShell(map[id]()); nextBtn.textContent = id==='review' ? 'Отправить бриф' : 'Далее'; backBtn.textContent = current===0 ? 'В начало' : 'Назад'; nextBtn.disabled = isSubmitting; bindInputs(); bindConditionalUi(); }
  function renderContact(){ return `<div class="field-stack">${inputField('name','Как вас зовут?',data.name,{required:true,placeholder:'Имя'})}${inputField('telegram','Ваш ник в Telegram',data.telegram,{required:true,placeholder:'@username',hint:'Можно указать с @ или без него.'})}</div>`; }
  function renderProject(){ const items=[['landing','Посадочная страница'],['registration','Регистрация на мероприятие / вебинар / интенсив'],['club','Страница клуба'],['vote','Голосование'],['quiz','Квиз / тест'],['catalog','Каталог'],['leadmagnet','Лид-магнит'],['sales','Страница продажи'],['interactive','Интерактивная механика'],['other','Другое']].map(([value,label])=>({value,label})); return `<div class="field-stack">${inputField('projectName','Название проекта / продукта',data.projectName,{required:true,placeholder:'Например: клуб, интенсив, голосование…'})}<div class="field"><div class="field-label required">Что нужно сделать?</div>${choices('projectTypes',items,data.projectTypes,{multi:true})}<div class="conditional ${data.projectTypes.includes('other')?'is-visible':''}" id="projectTypeOtherWrap">${inputField('projectTypeOther','Уточните, что именно',data.projectTypeOther,{placeholder:'Ваш вариант'})}</div></div></div>`; }
  const renderProjectDescription=()=>`<div class="field-stack">${areaField('projectDescription','Что должно получиться в результате?',data.projectDescription,{required:true,placeholder:'Например: нужна страница регистрации на офлайн-мероприятие, после регистрации человек должен попасть в Telegram-бот.'})}</div>`;
  const renderGoal=()=>`<div class="field-stack">${areaField('userGoal','Что в итоге должен сделать пользователь?',data.userGoal,{required:true,placeholder:'Зарегистрироваться, оставить заявку, купить, проголосовать, пройти тест…'})}${areaField('audience','Кто основная аудитория проекта?',data.audience,{required:true,placeholder:'Кто эти люди, для кого собираем страницу / MiniApp?'})}</div>`;
  function renderFunnelA(){ const traffic=[['tgChannel','Telegram-канал'],['bot','Telegram-бот'],['ads','Реклама'],['mail','Рассылка'],['getcourse','GetCourse'],['social','Соцсети'],['qr','QR-код'],['site','Сайт'],['other','Другое']].map(([value,label])=>({value,label})); return `<div class="field-stack"><div class="field"><div class="field-label required">Откуда пользователь попадает на страницу / в MiniApp?</div>${choices('trafficSources',traffic,data.trafficSources,{multi:true,cols:3})}<div class="conditional ${data.trafficSources.includes('other')?'is-visible':''}" id="trafficOtherWrap">${inputField('trafficOther','Уточните источник',data.trafficOther,{placeholder:'Ваш вариант'})}</div></div>${areaField('afterPage','Что происходит после страницы / MiniApp? Куда пользователь должен попасть дальше?',data.afterPage,{required:true,placeholder:'Например: после регистрации — в Telegram-бот, после оплаты — в закрытый клуб…'})}</div>`; }
  function renderFunnelB(){ const yn=[{value:'no',label:'Нет, пока без разных сценариев'},{value:'yes',label:'Да, есть разные сценарии'}]; return `<div class="field-stack">${areaField('funnel','Если уже есть понимание воронки — опишите её целиком',data.funnel,{placeholder:'Например: реклама → бот → MiniApp → регистрация → сообщения → мероприятие',hint:'Поле можно оставить пустым, если воронка пока не собрана.'})}<div class="field"><div class="field-label">Есть ли разные сценарии для пользователей?</div>${choices('hasScenarios',yn,data.hasScenarios)}</div><div class="conditional ${data.hasScenarios==='yes'?'is-visible':''}" id="scenariosWrap">${areaField('scenarios','Коротко опишите сценарии',data.scenarios,{placeholder:'Какие ветки уже известны?'})}</div></div>`; }
  const renderInside=()=>`<div class="field-stack">${areaField('mustHave','Есть ли что-то, что обязательно должно быть реализовано?',data.mustHave,{placeholder:'Например: форма регистрации, голосование, тест, личный кабинет, каталог, видео, расписание, результаты, закрытый контент.'})}</div>`;
  function renderTexts(){ const textStatus=[['ready','Тексты полностью готовы'],['adapt','Тексты есть, но их нужно адаптировать под страницу / MiniApp'],['materials','Есть материалы, из которых нужно собрать тексты'],['fromScratch','Тексты нужно подготовить с нуля']].map(([value,label])=>({value,label})); const textOwner=[{value:'yes',label:'Да, есть человек, который делает тексты'},{value:'needHelp',label:'Нет, нужна ваша помощь'}]; return `<div class="field-stack"><div class="field"><div class="field-label required">Как обстоят дела с текстами?</div>${choices('textStatus',textStatus,data.textStatus)}</div><div class="field"><div class="field-label">Есть ли кто будет делать тексты?</div>${choices('textOwner',textOwner,data.textOwner)}</div></div>`; }
  function renderDesign(){ const designStatus=[['ready','Есть готовый дизайн'],['designer','Есть дизайнер, который подготовит макеты'],['needDesigner','Нужен ваш дизайнер'],['adapt','Есть существующий стиль проекта, нужно адаптировать его под новую страницу / MiniApp'],['none','Визуального стиля пока нет']].map(([value,label])=>({value,label})); return `<div class="field-stack"><div class="field"><div class="field-label required">Как будем работать с дизайном?</div>${choices('designStatus',designStatus,data.designStatus)}</div>${areaField('designRefs','Есть ли фирменный стиль, брендбук или примеры страниц / приложений, на которые хочется ориентироваться?',data.designRefs,{placeholder:'Можно приложить ссылки или кратко описать, что нравится.'})}</div>`; }
  function renderIntegrations(){ const ints=[['getcourse','GetCourse'],['amo','AMO CRM'],['bitrix','Битрикс24'],['payments','Платёжная система'],['other','Другое'],['unknown','Пока не знаю'],['no','Не нужны']].map(([value,label])=>({value,label})); return `<div class="field-stack"><div class="field"><div class="field-label">Нужны ли интеграции с внешними сервисами?</div>${choices('integrations',ints,data.integrations,{multi:true})}<div class="conditional ${data.integrations.includes('other')?'is-visible':''}" id="integrationOtherWrap">${inputField('integrationOther','Уточните интеграции',data.integrationOther,{placeholder:'Ваш вариант'})}</div></div></div>`; }
  const renderDates=()=>`<div class="field-stack">${inputField('launchDate','Когда планируется запуск проекта / мероприятия?',data.launchDate,{type:'date',required:true})}${inputField('readyDate','К какой дате страница / MiniApp должна быть готова?',data.readyDate,{type:'date',required:true})}${areaField('importantDates','Есть ли важные даты внутри проекта?',data.importantDates,{placeholder:'Например: начало рекламы, открытие регистрации, старт продаж, эфир, мероприятие, закрытие регистрации.'})}</div>`;
  function renderAfter(){ const life=[['one','Под один конкретный запуск'],['ongoing','Для постоянного использования'],['repeat','Планируется использовать повторно и обновлять'],['unknown','Пока не определено']].map(([value,label])=>({value,label})); return `<div class="field-stack"><div class="field"><div class="field-label required">Проект создаётся:</div>${choices('projectLifetime',life,data.projectLifetime)}</div>${areaField('futureUpdates','Планируются ли дальнейшие изменения или обновления?',data.futureUpdates,{placeholder:'Если да — какие примерно?'})}</div>`; }
  const renderExtra=()=>`<div class="field-stack">${areaField('important','Что для вас особенно важно в этом проекте?',data.important,{placeholder:'Например: скорость, удобство на телефоне, мягкий стиль коммуникации, высокая конверсия…'})}${areaField('avoid','Есть ли что-то, что точно не хочется видеть или использовать?',data.avoid,{placeholder:'Какие решения, стили или механики вам точно не подходят?'})}${areaField('extra','Есть ли ещё что-то важное, что мне стоит знать до начала работы?',data.extra,{placeholder:'Любые дополнительные нюансы.'})}</div>`;
  function renderReview(){ return `<div class="review-hero"><div><div class="field-hint" style="margin-bottom:10px">Проверьте собранную сводку. При отправке ответы автоматически уйдут в таблицу.</div></div><img src="${assets.idea}" alt="Лисёнок с идеей"></div><div class="summary">${formatSummary(true).cards}</div>`; }
  function renderSuccess(){ progressShell.classList.add('is-hidden'); navRow.classList.add('is-hidden'); deviceNote.classList.add('is-hidden'); screenEl.innerHTML=`<div class="success-hero"><div class="success-copy"><div class="step-kicker">Готово</div><h2 class="step-title">Спасибо! Бриф отправлен</h2><p>Я получила ответы. Можно закрыть страницу или вернуться позже и заполнить новый бриф.</p><button class="btn btn-primary" id="restartBtn">Заполнить новый бриф</button></div><img src="${assets.sleep}" alt="Спящий лисёнок"></div>`; document.getElementById('restartBtn').addEventListener('click', ()=>{ localStorage.removeItem(STORAGE_KEY); data={...initialData}; renderIntro(); }); }
  function bindInputs(){ screenEl.querySelectorAll('input, textarea').forEach(el=>{ const evt=(el.type==='checkbox'||el.type==='radio')?'change':'input'; el.addEventListener(evt,handleFieldChange); }); }
  function handleFieldChange(e){ const {name,type,value,checked}=e.target; if(type==='checkbox'){ const arr=new Set(Array.isArray(data[name])?data[name]:[]); checked?arr.add(value):arr.delete(value); data[name]=[...arr]; } else { data[name]=value; } saveData(); bindConditionalUi(); }
  function bindConditionalUi(){ toggleWrap('projectTypeOtherWrap', data.projectTypes.includes('other')); toggleWrap('trafficOtherWrap', data.trafficSources.includes('other')); toggleWrap('scenariosWrap', data.hasScenarios==='yes'); toggleWrap('integrationOtherWrap', data.integrations.includes('other')); }
  function toggleWrap(id,show){ const el=document.getElementById(id); if(el) el.classList.toggle('is-visible',show); }
  function validateCurrent(){ const errors=[]; const req=(cond,msg)=>{if(!cond) errors.push(msg)}; const filled=v=>String(v||'').trim().length>0; const some=arr=>Array.isArray(arr)&&arr.length>0; switch(steps[current].id){ case 'contact': req(filled(data.name),'Введите имя.'); req(filled(data.telegram),'Введите Telegram.'); break; case 'project': req(filled(data.projectName),'Укажите название проекта.'); req(some(data.projectTypes),'Выберите формат проекта.'); if(data.projectTypes.includes('other')) req(filled(data.projectTypeOther),'Уточните свой вариант.'); break; case 'projectDescription': req(filled(data.projectDescription),'Опишите задачу.'); break; case 'goal': req(filled(data.userGoal),'Укажите целевое действие пользователя.'); req(filled(data.audience),'Укажите аудиторию проекта.'); break; case 'funnelA': req(some(data.trafficSources),'Выберите источник трафика.'); if(data.trafficSources.includes('other')) req(filled(data.trafficOther),'Уточните источник трафика.'); req(filled(data.afterPage),'Опишите, что происходит после страницы / MiniApp.'); break; case 'funnelB': if(data.hasScenarios==='yes') req(filled(data.scenarios),'Коротко опишите сценарии.'); break; case 'texts': req(filled(data.textStatus),'Выберите статус текстов.'); req(filled(data.textOwner),'Укажите, кто делает тексты.'); break; case 'design': req(filled(data.designStatus),'Выберите вариант по дизайну.'); break; case 'dates': req(filled(data.launchDate),'Укажите дату запуска.'); req(filled(data.readyDate),'Укажите дату готовности.'); break; case 'after': req(filled(data.projectLifetime),'Выберите формат жизни проекта.'); break; case 'integrations': if(data.integrations.includes('other')) req(filled(data.integrationOther),'Уточните интеграции.'); break; } return errors; }
  function payload(){ return { ...data, projectTypes:(data.projectTypes||[]).join(', '), trafficSources:(data.trafficSources||[]).join(', '), integrations:(data.integrations||[]).join(', '), sentAt:new Date().toISOString() }; }
  async function submitBrief(){ if(!SCRIPT_URL || SCRIPT_URL.includes('PASTE_YOUR')){ const msg=document.getElementById('validationMessage'); if(msg) msg.textContent='Не подключён Apps Script: добавьте ссылку /exec в app.js'; return; } isSubmitting=true; nextBtn.disabled=true; nextBtn.textContent='Отправляем...'; try { await fetch(SCRIPT_URL,{ method:'POST', mode:'no-cors', headers:{ 'Content-Type':'text/plain;charset=utf-8' }, body: JSON.stringify(payload()) }); localStorage.removeItem(STORAGE_KEY); renderSuccess(); } catch(e){ const msg=document.getElementById('validationMessage'); if(msg) msg.textContent='Не удалось отправить бриф. Проверьте ссылку Apps Script и доступ веб-приложения.'; nextBtn.disabled=false; nextBtn.textContent='Отправить бриф'; isSubmitting=false; } }
  function prettyDate(v){ if(!v) return '—'; const [y,m,d]=v.split('-'); return [d,m,y].filter(Boolean).join('.'); } function label(map,value){ return map[value]||value||'—'; } function labels(map,values){ return (values||[]).map(v=>map[v]||v).join(', ') || '—'; }
  function formatSummary(withCards){ const maps={ projectTypes:{landing:'Посадочная страница',registration:'Регистрация на мероприятие / вебинар / интенсив',club:'Страница клуба',vote:'Голосование',quiz:'Квиз / тест',catalog:'Каталог',leadmagnet:'Лид-магнит',sales:'Страница продажи',interactive:'Интерактивная механика',other:`Другое: ${data.projectTypeOther||''}`}, trafficSources:{tgChannel:'Telegram-канал',bot:'Telegram-бот',ads:'Реклама',mail:'Рассылка',getcourse:'GetCourse',social:'Соцсети',qr:'QR-код',site:'Сайт',other:`Другое: ${data.trafficOther||''}`}, textStatus:{ready:'Тексты полностью готовы',adapt:'Тексты есть, но их нужно адаптировать',materials:'Есть материалы, из которых нужно собрать тексты',fromScratch:'Тексты нужно подготовить с нуля'}, textOwner:{yes:'Да, есть человек, который делает тексты',needHelp:'Нет, нужна ваша помощь'}, designStatus:{ready:'Есть готовый дизайн',designer:'Есть дизайнер, который подготовит макеты',needDesigner:'Нужен ваш дизайнер',adapt:'Есть существующий стиль проекта, нужно адаптировать его',none:'Визуального стиля пока нет'}, integrations:{getcourse:'GetCourse',amo:'AMO CRM',bitrix:'Битрикс24',payments:'Платёжная система',other:`Другое: ${data.integrationOther||''}`,unknown:'Пока не знаю',no:'Не нужны'}, projectLifetime:{one:'Под один конкретный запуск',ongoing:'Для постоянного использования',repeat:'Планируется использовать повторно и обновлять',unknown:'Пока не определено'}, hasScenarios:{yes:'Да', no:'Нет'} };
    const sections=[ ['Контакт',`Имя: ${data.name||'—'}\nTelegram: ${data.telegram||'—'}`], ['О проекте',`Название: ${data.projectName||'—'}\nФормат: ${labels(maps.projectTypes,data.projectTypes)}\nЗадача: ${data.projectDescription||'—'}`], ['Цель',`Действие пользователя: ${data.userGoal||'—'}\nАудитория: ${data.audience||'—'}`], ['Воронка',`Источник трафика: ${labels(maps.trafficSources,data.trafficSources)}\nЧто дальше: ${data.afterPage||'—'}\nВоронка целиком: ${data.funnel||'—'}\nРазные сценарии: ${label(maps.hasScenarios,data.hasScenarios)}${data.hasScenarios==='yes'?`\nСценарии: ${data.scenarios||'—'}`:''}`], ['Что должно быть внутри',data.mustHave||'—'], ['Тексты',`Статус: ${label(maps.textStatus,data.textStatus)}\nКто делает: ${label(maps.textOwner,data.textOwner)}`], ['Дизайн',`Как работаем: ${label(maps.designStatus,data.designStatus)}\nОриентиры / референсы: ${data.designRefs||'—'}`], ['Интеграции',labels(maps.integrations,data.integrations)], ['Сроки',`Запуск: ${prettyDate(data.launchDate)}\nГотовность: ${prettyDate(data.readyDate)}\nВажные даты: ${data.importantDates||'—'}`], ['После запуска',`Формат проекта: ${label(maps.projectLifetime,data.projectLifetime)}\nОбновления: ${data.futureUpdates||'—'}`], ['Дополнительно',`Важно: ${data.important||'—'}\nНе хочется: ${data.avoid||'—'}\nДополнительно: ${data.extra||'—'}`] ]; return { cards: sections.map(([t,txt])=>`<div class="summary-card"><h3>${esc(t)}</h3><p>${esc(txt)}</p></div>`).join('') };
  }
  backBtn.addEventListener('click', ()=>{ if(current<=0) renderIntro(); else goTo(current-1); });
  nextBtn.addEventListener('click', async ()=>{ if(steps[current].id==='review'){ await submitBrief(); return; } const errors=validateCurrent(); const msgEl=document.getElementById('validationMessage'); if(errors.length){ if(msgEl) msgEl.textContent=errors[0]; return; } goTo(current+1); });
  renderIntro();
})();
